### ISSUE TITLE
bars with the same data displaying on top of each other

### ISSUE THREAD

**Issue by oomz** [planetoftheweb/d3#2]
When i have like:
chartData = [1, 2, 3,];
the chart displays the 3 bars correctly but when i have:
chartData = [1, 2, 3, 2];
the chart only displays 3 bars because the 4th data is the same with the 2nd, so their x attribute is the same. rendering the 4th bar in the place of the 2nd bar.

**Comment by planetoftheweb** [comment]
I'm not sure which video you're talking about, but it seems to work fine for me.
