### ISSUE TITLE
project should be watched and not attempted

### ISSUE THREAD

**Issue by cfont** [planetoftheweb/d3#5]
the readme instructions do not work. the code hasn't been updated in 3 years. the other issues reported haven't been addressed, not even with a "will not fix" type flag. the comments added to the Q&A portion of the LinkedIn Learning course basically says, "good luck". fairly disappointed. 

actually problems so far: 

* the instructions say to clone, npm install, and then run grunt. as far as I can tell, grunt isn't even part of this project and gulp fails to start because the package file doesn't have a start script defined

**Comment by cfont** [comment]
#6 will at least allow someone to start/run the project in a semi normal way

**Comment by cfont** [comment]
#7 will update the readme so that people can run the project and see the results in a browser without having to update gulp

**Comment by planetoftheweb** [comment]
Updated readme file.
