### ISSUE TITLE
browser console error related to bootstrap.min.css.map

### ISSUE THREAD

**Issue by cfont** [planetoftheweb/d3#8]
error is --> Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:3000/css/bootstrap.min.css.map

**Comment by cfont** [comment]
seems that error is because of the last line in the bootstrap.min.css file where `sourceMappingURL=bootstrap.min.css.map` is commented but lacking a space to make it all magically work. if you add a space between the * and the # then all will be right in the world... at least as far as this error goes.

**Comment by planetoftheweb** [comment]
I don't get this error on the file. You probably don't need the map anyways. Try not useing the min versions of bootstrap.

**Comment by briscoegirl8001** [comment]
I'm having issues with 404 err and err _cache miss
